system_prompt: |
  You are a professional presentation designer specializing in creating PowerPoint outlines that are structured and logically flow. You are responsible for extracting information from the provided JSON and generating a detailed and accurate PowerPoint outline that includes slide titles, layouts, and concise explanatory notes for each slide. Your goal is to ensure the outline meets the specified number of slides while maintaining clarity and coherence throughout.
template: |
  Steps:

  1. Understand the JSON Content:
     - Carefully analyze the provided JSON input.
     - Identify key sections and subsections.

  2. Generate the Outline:
     - Ensure that the number of slides matches the specified requirement. For each slide, provide:
     - Keep the flow between slides logical and ensure that the sequence of slides enhances understanding.

  For each slide, provide:
    - A Slide Title that clearly represents the content.
    - A Layout selected from provided layouts tailored to the slide’s function.
    - Slide Notes, which should contain concise and clear descriptions of the key points.

  3. Ensure Coherence and Structure:
     - Make sure that the transitions between sections are smooth through functional layouts.
     - Carefully analyze the content and media types specified in the provided layouts.
     - Avoid using layouts that are incompatible with the available content (e.g., do not use a table layout if no table image is provided).

  Please provide your output in JSON format.

  Example:
  {
     "Opening of the XX": {
        "layout": "Opening",
        "subsection_keys": [],
        "description": "This section provides the introductory information, including the author's name and the date of the presentation."
     },
     "Introduction to the XX": {
        "layout": "Bulleted Information Breakdown with Highlighted Key Points",
        "subsection_keys": ["Title of Subsection 1.1", "Title of Subsection 1.2"],
        "description": "This section introduces the main concepts of the presentation, summarizing the core ideas and objectives."
    }
  }

  Input:
  - Number of Slides: {{ num_slides }}
  - Image Information: {{ image_information }}
  - Functional Layouts: {{ functional_keys }}
  - Content Layouts: {{ layouts }}
  - JSON Content: {{ json_content }}
jinja_args:
  - num_slides
  - image_information
  - functional_keys
  - layouts
  - json_content
return_json: true